### ISSUE TITLE
How do I properly close the connection using this library? 

### ISSUE THREAD

**Issue by icepick3000** [ldab/ESP32_FTPClient#37]
After the upload I issue these commands;

```
  ftp.CloseFile();
  ftp.CloseConnection();
```

However eventually my server says "FTP error: 530 Sorry, the maximum number of connections (10) for your host are already connected.".
Is it possible to add a "QUIT" or "BYE" using this library to properly log off?

**Comment by ldab** [comment]
https://github.com/ldab/ESP32_FTPClient/blob/e5f89d4aa36c2a745ccf3d8d27bcad17410cb9af/src/ESP32_FTPClient.cpp#L133

**Comment by UNOSweeper** [comment]
Hi ldab. Reading your README.md I see you have used 000webhost.com for your experiments. Because using your examples which I have still problems with, using my own FTP server I have made an account at 000webhost and the first begin is there. I have uploaded a simple html file with a test picture. But how do you get the FTP servername, -user and -passw? Also everytime when I have logged on I get the page https://www.000webhost.com:80/cpanel-login that delivers a page in my Edge browser saying that the connection to this URL is not safe. Refreshing does not help. Start-up problems, I hope?

**Comment by ldab** [comment]
https://www.000webhost.com/website-faq/where-can-i-find-my-ftp-information-11

Port 80 is unsecure, the browser will always complain.
